services:
  frontend-builder:
    build:
      context: ./frontend
      dockerfile: -
      contents: |
        FROM node:20
        WORKDIR /app
        COPY package*.json ./
        RUN npm install
        COPY . .
        CMD ["npm", "run", "build"]
    image: ${DOCKER_USERNAME}/frontend-builder:latest
    container_name: frontend-builder-container
    volumes:
      - ./frontend:/app
    networks:
      - fs-app

  frontend-nginx:
    build:
      context: ./frontend
      dockerfile: -
      contents: |
        FROM nginx:latest
        COPY dist /usr/share/nginx/html
        COPY nginx.conf /etc/nginx/conf.d/default.conf
    image: ${DOCKER_USERNAME}/frontend-nginx:latest
    container_name: frontend-nginx-container
    ports:
      - "5173:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend-builder
      - backend
    networks:
      - fs-app
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: -
      contents: |
        FROM node:20
        WORKDIR /app
        COPY package*.json ./
        RUN npm install
        COPY . .
        CMD ["npx", "nodemon", "-L", "index.js"]
    image: ${DOCKER_USERNAME}/backend:latest
    container_name: backend-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/ums
    depends_on:
      - mongo
    networks:
      - fs-app
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27016:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - fs-app
    restart: unless-stopped
    command: mongod --quiet --logpath /dev/null

volumes:
  mongo-data:
    name: mongo-data

networks:
  fs-app:
    driver: bridge
    name: fs-app
