services:
  frontend-builder:
    build: 
      context: ./frontend
      labels:
        - "com.docker.compose.project=fs-app"
    image: ${DOCKER_USERNAME}/frontend-builder:latest
    container_name: frontend-builder-container
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run build"
    networks:
      - fs-app

  frontend-nginx:
    build:
      context: ./frontend
      labels:
        - "com.docker.compose.project=fs-app"
    image: ${DOCKER_USERNAME}/frontend-nginx:latest
    container_name: frontend-nginx-container
    ports:
      - "5173:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend-builder
      - backend
    networks:
      - fs-app
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      labels:
        - "com.docker.compose.project=fs-app"
    image: ${DOCKER_USERNAME}/backend:latest
    container_name: backend-container
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npx nodemon -L index.js"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/ums
    depends_on:
      - mongo
    networks:
      - fs-app
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27016:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - fs-app
    restart: unless-stopped
    command: mongod --quiet --logpath /dev/null

volumes:
  mongo-data:
    name: mongo-data

networks:
  fs-app:
    driver: bridge
    name: fs-app
