-name: Node.js CI
+name: Node.js CI with Lockfiles

 jobs:
   build:
     runs-on: ubuntu-latest

     strategy:
       matrix:
         node-version: [20.x]

     steps:
     - uses: actions/checkout@v4
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v4
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
-    - name: Install Dependencies for Backend
+    - name: Install Dependencies and Generate Lockfile for Backend
       run: |
         cd backend
+        npm install --package-lock
         npm ci
-    - name: Install Dependencies for Frontend
+    - name: Install Dependencies and Generate Lockfile for Frontend
       run: |
         cd frontend
+        npm install --package-lock
         npm ci
     - name: Build Backend
       run: |
